spring:
  datasource:
          url: jdbc:mysql://sh-cdb-j7xx94hb.sql.tencentcdb.com:63281/touchlearn?useUnicode=true&characterEncoding=utf-8
          username: root
          password: 19960411likang
          driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cheyfly.touchlearn.common.dao

